openapi: 3.1.0

info:
  title: Swagger Skill Tracker - OpenAPI 3.0
  version: 0.1.1
  description: |-
    Swagger documentation for skill tracker api developed by Max Saunders
  contact:
    email: saunders.max.k@gmail.com

servers:
  - url: localhost:8000

tags:
  - name: person
    description: Details about your teammate

paths:
  /people:
    get:
      summary: Returns list of users
      description: Optional
      responses:
        '200':
          description: A JSON array of users - Person type
  /people/{id}:
    get:
      summary: Return details for a single user
      responses:
        '200':
          description: A JSON object of user - Person type
        '500':
          description: User cannot be found for given id

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: string
          example: 123456
        name:
          type: string
          example: Max Cannon
        skills:
          type: array
          items:
          example: [{}]
        topSkill:
          type: skill
          example: { id: '123456', name: 'ReactJS', rating: 4 }
    Skill:
      type: object
      properties:
        id:
          type: string
          example: 123456
        name:
          type: string
          example: Java
        description:
          type: string
          example: The programming language java
    UserSkill:
      type: object
      properties:
        id:
          type: string
          example: 123456
        name:
          type: string
          example: Java
        rating:
          type: number
          example: 4
